### ISSUE TITLE
Can't start new threads

### ISSUE THREAD

**Issue by humanityliberator** [spyboy-productions/CloakQuest3r#11]
Starting threads...
Traceback (most recent call last):
  File "/Users/admin/CloakQuest3r/cloakquest3r.py", line 297, in <module>
    find_subdomains_with_ssl_analysis(domain)
  File "/Users/admin/CloakQuest3r/cloakquest3r.py", line 155, in find_subdomains_with_ssl_analysis
    thread.start()
  File "/usr/local/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 994, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

**Comment by thisisshubhamkumar** [comment]
what OS u r using?  and what domain u passed?

This occurs when the system runs out of resources.

set ulimit to unlimited, this should fix the issue...

use these commands
```
ulimit -a  # Check current limits
ulimit -u <new_limit>  # Set a higher limit for max user processes
```
https://www.howtogeek.com/805629/too-many-open-files-linux/#:~:text=If%20you%20see%20the%20%22Too,%22ulimit%20-n%202048

Let me know if it worked or not.
