### ISSUE TITLE
UnicodeEncodeError: 'charmap'

### ISSUE THREAD

**Issue by raf-lii** [spyboy-productions/CloakQuest3r#3]
I got an error when running the code for the first time

`
Traceback (most recent call last):
  File "C:\Users\62897\CloakQuest3r\cloakquest3r.py", line 167, in <module>
    print_banners()
  File "C:\Users\62897\CloakQuest3r\cloakquest3r.py", line 44, in print_banners
    print(f'{G} \u2570\u27a4 {Y}Twitter      : {W}{twitter_url}')
  File "C:\Users\62897\AppData\Local\Programs\Python\Python312\Lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "C:\Users\62897\AppData\Local\Programs\Python\Python312\Lib\site-packages\colorama\ansitowin32.py", line 177, in write
    self.write_and_convert(text)
  File "C:\Users\62897\AppData\Local\Programs\Python\Python312\Lib\site-packages\colorama\ansitowin32.py", line 202, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\62897\AppData\Local\Programs\Python\Python312\Lib\site-packages\colorama\ansitowin32.py", line 210, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Users\62897\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1-2: character maps to <undefined>
`

**Comment by thisisshubhamkumar** [comment]
Thanks for letting us know. The new update is live just git pull and try to run the tool if it still throws an error let us know.

we haven’t tested this tool on Windows yet it is working fine on Mac terminal and Android Termux.

The error you were encountering is specific to Windows and the way it handles character encoding in the console. On Windows, the default character encoding for the console is often "cp1252," and it doesn't support certain Unicode characters.

The error is because the arrow symbols (╰➤) are not supported in the default Windows encoding, causing a UnicodeEncodeError.

**Comment by raf-lii** [comment]
hello, i'm already try with the new update and still got the same response

**Comment by thisisshubhamkumar** [comment]
We have tested it on the Windows terminal it works fine. use windows Terminal(download it from store) instead of CMD
